name: EasyCloud Build

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'apps/**/appinfo/info.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  push:
    branches:
      - main
      - master
      - stable*

env:
  TARGET_PACKAGE_NAME: easy-storage.zip

permissions:
  contents: read

jobs:
  easycloud-build:
    runs-on: ubuntu-latest

    name: easycloud-build
    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Zip dependencies
        run: |
          echo "zip relevant files to $TARGET_PACKAGE_NAME"
          zip -r "${{ env.TARGET_PACKAGE_NAME }}" 3rdparty/ apps/ custom-apps/ apps-external/ config/ core/ dist/ lib/ ocs/ ocs-provider/ resources/ themes/ AUTHORS composer.json composer.lock console.php COPYING cron.php index.html index.php occ package.json package-lock.json public.php remote.php robots.txt status.php version.php -x "apps/theming/img/background/**" -x "apps/*/tests/**" -x "apps-external/*/tests**" -x "**/cypress/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easy-storage-build-${{ github.sha }}
          path: ${{ env.TARGET_PACKAGE_NAME }}

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention
