name: EasyCloud Build

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'apps/**/appinfo/info.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  push:
    branches:
      - tl/dev/HDFRONT-6801-build-frontend-artifact

env:
  TARGET_PACKAGE_NAME: easy-storage.zip
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  easycloud-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    name: easycloud-build
    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Zip dependencies
        env:
          GIT_REF: ${{ github.ref }}
          GIT_SHA: ${{ github.sha }}
        # Doc:
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        run: |
          buildDate=$(date +%s)
          buildRef=${{ github.ref }}
          buildSha=${{ github.sha }}
          jq -n --arg buildDate "$buildDate" --arg buildSha "$GIT_SHA" --arg buildRef "$GIT_REF" '{buildDate: $buildDate, buildSha: $buildSha, buildRef: $buildRef}' > version.json

          echo "version.json created"
          jq . version.json

          echo "zip relevant files to ${{ env.TARGET_PACKAGE_NAME }}"
          zip -r "${{ env.TARGET_PACKAGE_NAME }}" \
            3rdparty/ \
            apps/ \
            custom-apps/ \
            apps-external/ \
            config/ \
            core/ \
            dist/ \
            lib/ \
            ocs/ \
            ocs-provider/ \
            resources/ \
            themes/ \
            AUTHORS \
            composer.json \
            composer.lock \
            console.php \
            COPYING \
            cron.php \
            index.html \
            index.php \
            occ \
            package.json \
            package-lock.json \
            public.php \
            remote.php \
            robots.txt \
            status.php \
            version.php \
            version.json  \
          -x "apps/theming/img/background/**" \
          -x "apps/*/tests/**" \
          -x "apps-external/*/tests**" \
          -x "**/cypress/**"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.TARGET_PACKAGE_NAME }}

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention
