name: EasyCloud Build

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'apps/**/appinfo/info.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  push:
    branches:
      - main
      - master
      - stable*
      - mk/poc/*

env:
  TARGET_PACKAGE_NAME: easy-storage.zip
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  easycloud-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    name: easycloud-build
    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Zip dependencies
        run: |
          echo "zip relevant files to $TARGET_PACKAGE_NAME"
          zip -r "${{ env.TARGET_PACKAGE_NAME }}" 3rdparty/ apps/ custom-apps/ apps-external/ config/ core/ dist/ lib/ ocs/ ocs-provider/ resources/ themes/ AUTHORS composer.json composer.lock console.php COPYING cron.php index.html index.php occ package.json package-lock.json public.php remote.php robots.txt status.php version.php -x "apps/theming/img/background/**" -x "apps/*/tests/**" -x "apps-external/*/tests**" -x "**/cypress/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easy-storage-build-${{ github.sha }}
          path: ${{ env.TARGET_PACKAGE_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create Dockerfile
        run: |
          DOCKER_BUILD_FILE=$(cat << EOF
          FROM busybox as builder
          COPY ./${{ env.TARGET_PACKAGE_NAME }} /
          WORKDIR /builder
          RUN unzip /${{ env.TARGET_PACKAGE_NAME }} -d /builder

          FROM scratch
          WORKDIR /app
          VOLUME /app
          COPY --from=builder /builder /app
          EOF
          )
          echo "$DOCKER_BUILD_FILE" > Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention
